
% Recommended config parameters to use for analysing ephys data.
% Use with ExplainedVarianceReactivation.

inclusionCriteria = struct(...
    'rats', {{'Quirinius', 'Severus', 'Trevor'}},...
    'sessions', struct(...
        'initialLearningOnly', true,...
        'skipEarliest', true,...
        'significantPerformanceThreshold', 1/3,...
        'minimumNCA1Cells', 5,...
        'minimumNVStrCells', 5),...
    'cells', struct(...
        'rewardResponsive', true,...
        'minimumFiringRate', 0));
    
analysisConfig = struct(...
        'postDuration', NaN,...
        'rippleActivityMode', 'equalise',...
        'nRipples', NaN,...
        'gaussianWindowWidth', 0.1,...
        'controlCriterion', 'minimalContributions',...
        'reactivationQuantileThreshold', 0.1);
